apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ieam-provisioner-cluster-admin
subjects:
  - kind: ServiceAccount
    name: ieam-provisioner
    namespace: openhorizon-agent
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
